# Generated by Django 4.1.2 on 2022-12-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Order Accepted', 'Order Accepted'), ('Delivered Successfully', 'Delivered Successfully'), ('Order Cancelled', 'Order Cancelled')], default='Pending', max_length=55),
        ),
    ]
